# Use postgres/example user/password credentials
version: '3.1'
volumes:
  sv_pg_data:
services:
  db:
    image: postgres:13
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
        - sv_pg_data:/var/lib/postgresql/data
